# Generated by Django 4.1.3 on 2022-12-07 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_profile_followers_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='get_liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
